{
  "taskDefinition": {
    "family": "hello-world",
    "containerDefinitions": [
      {
        "name": "downloader",
        "image": "627610429839.dkr.ecr.ap-southeast-1.amazonaws.com/downloader:6a57b99",
        "cpu": 100,
        "portMappings": [
          {
            "protocol": "tcp",
            "containerPort": 80,
            "hostPort": 80
          }
        ],
        "memory": 128,
        "essential": true
      }
    ]
  }
}